### ISSUE TITLE
Vue-智能文字全文朗读、短句播放、汉字认读

### ISSUE THREAD

**Issue by forestxieCode** [forestxieCode/blog#3]
### 智能文字跟读
需求：在一篇文字中，点击汉字认读，语言播放相应的汉字，文字变成红色；点击短句播放，点击文中的某一句话，实现朗读并且相应的，该句文字的背景颜色也需要跟随音频的进度显示动画；点击全文朗读，基于短句播放朗读全文，效果图如下。

![](https://user-gold-cdn.xitu.io/2020/7/21/173702fac7b9d237?w=794&h=388&f=gif&s=308869)

### 需求分解
1. 渲染文字；可能要注意段，句，字的区分，如要实现汉字认读，那么每一个字对应该需要对应一个音频，短句播放，每一句又对应一个音频，全文朗读，可以基于短句播放循环播放每一句。所以渲染时，要注意每个功能的处理。
2. 汉字认读；点击每个汉字，获取汉字去文件库获取对应的音频文件，字也相应的变成红色。可能这个实现起来还是比较简单的。
3. 短句播放（重点）；一、要获取每句话的播放时长。二、背景色的动画也要跟着播放时长变化。三、播放音频。（下面会细讲这个要注意的点）
4. 全文朗读；相对简单，只要实现短句播放，那么循环，每一句话，就是能实现整篇文章的朗读。

### 短句播放细讲
可能这难点就是背景色的动画了，这个自己也是琢磨了大半天，不知道以何种元素做动画。当时一个朋友提出一个方案就是，渲染两种文字，一种带有颜色的，一个不带颜色，根据音频的长度，用带有颜色的文字去覆盖无颜色的，
#### 存在的缺陷
这个有一个缺陷，就是必须带有颜色的文字，和不带有颜色的位置要完全吻合才行，不然渲染起来效果不佳，又因为时移动端，很多设备的宽度存在差异。
 
 
### 较完美的解决方案（background-size）
利用background-size做css的动画，针对它的with宽度做动画效果。

    1.得到每句音频的时长，
    2.设置每句话的`animation-duration` 的时长
    3.animation-name的变动元素为每句话的background-size的宽度
    4.animation-timing-function：选择ease-in-out 即可
```css
@keyframes line-left-to-right {
  from {
    background-size: 0% 100%;
  }
  to {
    background-size: 100% 100%;
  }
}
.left-to-right-animation {
  animation-name:line-left-to-right!important;
  animation-duration:3s;
  animation-timing-function:ease-in-out!important;
}
```
因为不能将每句话设置成块级元素，块级元素会独占一行，那样显示效果不会很美观。所有必须使用行内元素，那么就会存在换行，那么`background-size`也是可以做到换行动画的。

![](https://user-gold-cdn.xitu.io/2020/7/21/173705e9185028e0?w=1920&h=1920&f=jpeg&s=135165)

### 总结
学以智用，做一个愉快的板砖手，项目开源地址，有兴趣可以看下哈，记得star!!! [项目地址](https://gitee.com/CodeOfPassion/FollowThePassage "项目地址")
